### ISSUE TITLE
EOF error when building on Windows

### ISSUE THREAD

**Issue by KorbsStudio** [KorbsStudio/electron-builder-sample#1]
![image](https://user-images.githubusercontent.com/51213244/120952100-55f20900-c718-11eb-913c-d58b14a3d5a3.png)
This repo is also built to provide a GitHub Actions example, which builds on Windows too.

When it's ready to build on Windows(running `npm run build`), an EOF error occurs in Electron Builder, and I'm not sure how to fix this issue.

Output:
```
> electron-builder-sample@1.0.0 build D:\a\electron-builder-sample\electron-builder-sample
> electron-builder build -p always

  • electron-builder  version=22.10.5 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=win32 arch=x64 electron=13.1.1 appOutDir=dist\win-unpacked
  • Unpacking electron zip  zipPath=undefined
  • downloading     url=https://github.com/electron/electron/releases/download/v13.1.1/electron-v13.1.1-win32-x64.zip size=83 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v13.1.1/electron-v13.1.1-win32-x64.zip duration=508ms
  ⨯ EOF
github.com/develar/go-fs-util.CloseAndCheckError
	C:/Users/develar/go/pkg/mod/github.com/develar/go-fs-util@v0.0.0-20190620175131-69a2d4542206/fs.go:117
github.com/develar/app-builder/pkg/fs.ReadFile
	C:/Users/develar/Desktop/app-builder/app-builder/pkg/fs/file.go:40
github.com/develar/app-builder/pkg/icons.validateImageSize
	C:/Users/develar/Desktop/app-builder/app-builder/pkg/icons/icon-converter.go:122
github.com/develar/app-builder/pkg/icons.doConvertIcon
	C:/Users/develar/Desktop/app-builder/app-builder/pkg/icons/icon-converter.go:180
github.com/develar/app-builder/pkg/icons.ConvertIcon
	C:/Users/develar/Desktop/app-builder/app-builder/pkg/icons/icon-converter.go:56
github.com/develar/app-builder/pkg/icons.ConfigureCommand.func1
	C:/Users/develar/Desktop/app-builder/app-builder/pkg/icons/icon-converter.go:33
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	C:/Users/develar/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	C:/Users/develar/Desktop/app-builder/app-builder/main.go:90
runtime.main
	c:/go/src/runtime/proc.go:204
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1374  
  ⨯ D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                      Error: D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                          at ChildProcess.<anonymous> (D:\a\electron-builder-sample\electron-builder-sample\node_modules\builder-util\src\util.ts:243:14)
                                                                                                                                                                          at Object.onceWrapper (events.js:483:26)
                                                                                                                                                                          at ChildProcess.emit (events.js:376:20)
                                                                                                                                                                          at maybeClose (internal/child_process.js:1055:16)
                                                                                                                                                                          at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
                                                                                                                                                                      From previous event:
                                                                                                                                                                          at processImmediate (internal/timers.js:462:21)
                                                                                                                                                                      From previous event:
                                                                                                                                                                          at WinPackager.signApp (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\winPackager.ts:357:27)
                                                                                                                                                                          at WinPackager.doSignAfterPack (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\platformPackager.ts:270:16)
                                                                                                                                                                          at WinPackager.doPack (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\platformPackager.ts:255:7)
                                                                                                                                                                          at WinPackager.pack (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\platformPackager.ts:115:5)
                                                                                                                                                                          at Packager.doBuild (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\packager.ts:434:9)
                                                                                                                                                                          at executeFinally (D:\a\electron-builder-sample\electron-builder-sample\node_modules\builder-util\src\promise.ts:12:14)
                                                                                                                                                                          at Packager._build (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\packager.ts:369:31)
                                                                                                                                                                          at Packager.build (D:\a\electron-builder-sample\electron-builder-sample\node_modules\app-builder-lib\src\packager.ts:333:12)
                                                                                                                                                                          at executeFinally (D:\a\electron-builder-sample\electron-builder-sample\node_modules\builder-util\src\promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-builder-sample@1.0.0 build: `electron-builder build -p always`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-builder-sample@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2021-06-07T02_36_23_734Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by KorbsStudio** [comment]
Issue found: **Damaged ICO icon**
